### ISSUE TITLE
List Template in Wiki

### ISSUE THREAD

**Issue by MMetze** [BigJk/snd#11]
I don't know how list templates work, or what their actual purpose is. Need clarification to describe in wiki.

https://github.com/BigJk/snd/wiki/Templates

**Comment by BigJk** [comment]
The List Templates defines if and what should be shown under the name of each entry in the entry list. For Example: If you want to have the Spell Level and School under every entry in Spells (e.g. ``2nd-level Transmutation``) you can use:

```
<span style="font-size: 14px">{{ it.level }} {{ it.school }}</span>
```

Result:
![](https://i.imgur.com/I83EfSO.png)

It's also just Nunjucks :)

**Comment by MMetze** [comment]
Updated the wiki section.
