### ISSUE TITLE
Sometimes Characters instead of Image is printed

### ISSUE THREAD

**Issue by BigJk** [BigJk/snd#21]
This behaviour is sometimes encountered on mac while using cups. Printing characters instead of a image might indicate that the printer didn't correctly receive the ``raster image`` command and is trying to print the image bytes as characters. It needs to be investigated when this happens and if it's a problem with cups, the printer or S&D itself.

**Comment by nbadal** [comment]
Might be related to buffer size - at least in the case of my printer (Citizen CT-S310) images taller than 384x2400 or so fail consistently.

One idea floated was to split renders, though we'd need to make sure there aren't margins between images

**Comment by BigJk** [comment]
Buffer size is definitely one error source depending on printer and yes, we should check if we can print splitted images without margins 😄

Sadly that wouldn't explain the problem I encounter at the moment

On a M1 Macbook:
- First CUPS print works
- Every print after that fails with gibberish even if the image is just 10 pixel height
- Only turning printer on / off before each print works -> Corrupted / print buffer not cleared after CUPS print?
- Writing directly to the virtual USB COM of the printer via libusb everything works normally. No gibberish.

@frshbeetz confirmed that this doesn't happen on his Intel + Mac Setup. Both using CUPS 2.3.4. I will try to dig out some other USB printer I have and check if the same problem happens with CUPS.

**Comment by BigJk** [comment]
I dug out my old Zjiang ZJ-5890K which was the first printer I used for the project and only has 58mm. I can print even a 1 meter long template without any gibberish. Consecutive cups prints also don't corrupt the printing.

Then I retried some more with the Zjiang ZJ-8330. After fully unplugging until all power is gone, then setting **Force Standard Mode** to on and **Explicit Initialization** to off cups decided to start working again. No more gibberish. Seems like it's very picky about these settings with CUPS 🤔

**Comment by BigJk** [comment]
@nbadal I changed the printing so that chunked prints work. I verified with my printer that no margins were present. You can set it up in the settings. 

- **Split Height**: Height in pixel of each chunk
- **Split Delay**: Delay in ms after each chunk print. This might be useful for direct usb printing were we don't want to overflow the buffer with too much data in a short time. For cups this can probably stay at 0 as cups itself will be a bit slower with sending prints.

**Comment by BigJk** [comment]
Thanks to github making the m1 runner available to open source S&D now comes with libusb releases for arm (m1,mX) builds. This should make it possible to avoid the weird behavior of CUPS on arm based macs. I will close this issue for now.
