### ISSUE TITLE
Standardized Data Sources

### ISSUE THREAD

**Issue by teamcoltra** [BigJk/snd#27]
So I was writing up an issue to say that it sucks that the DnD community hasn't started to standardize their data for stuff like this, but that it would be great if you supported More Purple More Better format and the Fight Club format because they have active communities keeping their compendiums up to date and you can get various additional content.

But it looks like Fight Club is already working with people to standardize their system and as it has a huge wealth of stuff I don't think you would need to bother with MPMBs.

Here is a blog post about the Fight Club system https://donfarland.com/technology/fight-club-5-compendium-update which also links to their GitHub.

It's all xml so it should be straight forward to incorporate

**Comment by BigJk** [comment]
Thanks for the information! I didn't knew about the Fight Club 5 Compendium, but that looks really useful. I will try to incorporate it soon 😄
