### ISSUE TITLE
Trojan warnig from windows defender

### ISSUE THREAD

**Issue by Brazier85** [BigJk/snd#28]
Hello, on startup windows defender is blocking your application with the following message:

![image](https://user-images.githubusercontent.com/1213924/209561404-d54c1631-b6b9-432c-a4d3-08dee02e47aa.png)

Can you pls take a look into this issue or can you tell me what the `leakless.exe` file is?

**Comment by BigJk** [comment]
Hello Brazier,

never heard of anyone experiencing a trojan warning so far.

I dug a bit and leakless is a utility (https://github.com/ysmood/leakless) to "Run sub-process and make sure to kill it when the parent process exits.". It is used by https://github.com/go-rod/rod which S&D uses to control a chrome instance to create images from HTML. It's probably used to make sure that all sub-processes are killed correctly if rod shuts down.

Does this information help?

**Comment by BigJk** [comment]
Related Issues:

https://github.com/go-rod/rod/issues/739
https://github.com/go-rod/rod/issues/720
https://github.com/go-rod/rod/issues/734

**Comment by Brazier85** [comment]
okay, thank you. I will recover the file and ignore the alert :)

**Comment by BigJk** [comment]
As of v0.6.3 leakless is explicitly disabled on windows. I hope this will avoid any further false positive warnings 👍
