### ISSUE TITLE
Open Dashboard in Browser

### ISSUE THREAD

**Issue by rauchmo** [BigJk/snd#31]
An Option would be great to "host" the snd Dashboard on a server.
So that i could install snd on an raspberry pi + connected printer and connect to it with an standard Windows Browser.

But all in all awesome project :)

**Comment by BigJk** [comment]
This is already supported. You can use the matching ``linux-arm`` ``headless`` build for a RPi. Headless means it's just the web-server without the GUI window. You can still open the dashboard over the network ``http://{YOUR_IP}:7123`` and do printing etc. Only some Import & Export options are not supported in headless mode as native open folder / file dialogs are needed. 

Headless is not tested a lot though as the main target is the windowed version. If you find any bugs in the headless version please let us know 😄 and you might need to use v0.6.2 as the latest version introduced a change where I still need to implement a headless fallback

**Comment by rauchmo** [comment]
Ah nice, thx for the fast response.
Sorry about the question, i didnt see the download option for the headless build ^^

**Comment by BigJk** [comment]
No Problem! If any problems come up feel free to open new issues or drop by our Discord.
