### ISSUE TITLE
Bundling MacOS builds into .app folders

### ISSUE THREAD

**Issue by BigJk** [BigJk/snd#39]
For MacOS we should switch to distributing a complete .app folder in the future, so that S&D is a Application that can be dropped into the application folder with it's own Icon.

Target folder structure would probably be:
```
Sales & Dungeons.app/
└── Contents
    ├── Info.plist
    ├── MacOS
    │   └── snd
    │   └── frontend/...
    │   └── data/...
    │   └── version.txt
    └── Resources
        └── icon.icns
```

Additionally we should change the default ``userdata`` folder on MacOS so that data will be kept outside of the app bundle. Something like ``~/Documents/Sales & Dungeons/``. That way the app can easily be updated by just overwriting.

Info:
- https://developer.apple.com/library/content/documentation/CoreFoundation/Conceptual/CFBundles/BundleTypes/BundleTypes.html#//apple_ref/doc/uid/10000123i-CH101-SW19
- https://medium.com/@mattholt/packaging-a-go-application-for-macos-f7084b00f6b5
- https://gist.github.com/mholt/11008646c95d787c30806d3f24b2c844

**Comment by nbadal** [comment]
I've spent a few days on this already 😁 hopefully getting something working in the next week or two

**Comment by BigJk** [comment]
Great. Than I will wait for your results 👍

**Comment by BigJk** [comment]
Should be solved with: https://github.com/BigJk/snd/releases/tag/v1.0.0-rc3
