### ISSUE TITLE
feature: Data skeleton define variable types (i.e. Lists, Checkboxes, etc.)

### ISSUE THREAD

**Issue by MrG4dget** [BigJk/snd#45]
Using snd frequently in the past weeks, I must say, this tool is "THE SH*IT" (as in awesome)!

However when I add new entries manually, I found, that it would be super useful, to have data fields, that can be set int the data skeleton. For example:
"requires_attunement": (bool)"" Would show up in "create new entry" as a checkbox (inspiration taken by the already existing global config feature)

Also lists would help a lot like rarityies, types (i.e Wondorous item, Ring, Armour, etc.)

Cheers! :)

**Comment by MrG4dget** [comment]
Sorry, just saw that someone already mentioned this ^^ 
https://github.com/BigJk/snd/issues/25

**Comment by BigJk** [comment]
Glad S&D is so useful for you! I'm currently at the mid-point of writing my thesis, that's why S&D is moving a bit slower atm. I hope that after I'm done with my thesis I can spend more time at it again and implement features like that! 😄
