### ISSUE TITLE
[Request] Add support for LM Studio's local API server

### ISSUE THREAD

**Issue by RandomNiiChan** [BigJk/snd#59]
[LM Studio](https://lmstudio.ai/) allows to easily run any HuggingFace gguf LLM locally (LLama, Mistral, etc) and open an API endpoint.

![image](https://github.com/BigJk/snd/assets/32325398/e171d83b-ab0d-40ab-8794-c93c80b7b501)

Lightweight models offer satisfying results and can easily be ran with 16GB RAM and 8GB VRAM. Would that be possible to add support for a self-hosted API server in the AI section?

**Comment by BigJk** [comment]
Never heard about LM Studio but that looks interesting. As this seems to use a OpenAI compatible API this should be really easy to add. Great suggestion! I will add it as soon as I find the time 😄

**Comment by BigJk** [comment]
Thanks again for the cool idea!

Just released a version that supports local llms. Just select "Custom (e.g. Local)" and throw the URL into the "Custom URL". I tried it with LM Studio with ``StableLM Zephyr 3B`` and it worked 👍 Feel free to test and check if anything isn't working as expected 😀 

https://github.com/BigJk/snd/releases/tag/v1.0.0-rc2 

<img width="1028" alt="image" src="https://github.com/BigJk/snd/assets/1621820/a742b2b9-2f86-4703-9818-0ddc437f0bcd">
