### ISSUE TITLE
QR Code generation

### ISSUE THREAD

**Issue by MrG4dget** [BigJk/snd#62]
Just in case someone can use this:

Wanted to create a QR code that opens the URL to the dndbeyond entry of a spell. Got it working with the following:

```html 
<img style="display: block; margin-left: auto; padding: 20px;  margin-right: auto; width: 50%;" 
src="{{"https://api.qrserver.com/v1/create-qr-code/?size=150x150&data="+"https://www.dndbeyond.com/spells/"+config.name | replace(" ","-") | lower+""}}"></img>
```

So if the config has the Spells name, it should create the correct QR code.
![Screenshot 2024-05-20 160019](https://github.com/BigJk/snd/assets/3408565/1ebfcf96-25b1-4f42-9672-a58cbc965b1f)

**Comment by BigJk** [comment]
Nice idea! 😍 

Because this is not a bug/issue maybe we can start a useful snippets discussion here: https://github.com/BigJk/snd/discussions/63

So that we can keep the issues for bugs and problems. It would be awesome if you could post this snippet again over there ❤️
