### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by BigJk** [BigJk/snd#9]
There is still a lot of documentation missing at the moment.

### Documentation needed for:
- Building
- Printing Types
- Templating
- Scripting

I would really like to keep the ``README.md`` from being bloated too much. Do you guys think the Github Wiki is a good enough place for the documentation or is there any need for a more dedicated / external documentation solution?

**Comment by MMetze** [comment]
I would say that the Wiki here is enough. Most people will use git and compile themself, so they are already on git. Also it makes it easy if someone wants to help out with a specific topic.
